services:
  - type: web
    name: clearsight-pollution-monitor
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
